---
output: pdf_document
---
####Introduction

Ca^2+^ plays an essential role in various neural activities, including learning and memory. Ca^2+^ influx to spines can result in spine enlargement; Ca^2+^ signals enter the soma can affect CREB activation which further regulate gene expressions and protein synthesis. How Ca^2+^ signals travel through the surface channels and reach the nucleus has been debated over a decade. One hypothesis states that Ca^2+^ signals spread into the nucleus primarily by diffusion and the diffusion from cytolsol raises the nucleus free Ca^2+^ level. However, the Ca^2+^ signals could be easily get lost during diffusion because Ca^2+^ can be captured by lots of buffer proteins. Another line of studies indicate that Ca^2+^ molecules are transported to the nucleus by carrier proteins. In particular the holoenzymes \(\gamma\)-CaMKIIs are suggested to act as carriers instead of kinase and are possibly phosphorylated by \(\beta\)-CaMKIIs. However, the inter-holoenzyme interactions involved in the cascade are a concern for speed of the Ca^2+^ signal propagation. In addition, holoenzynmes have to interact with NPCs (Nuclear Pore Complex) to enter the nucleus. By contrast, the nuclear membrane is hardly a diffusion barrier for free Ca^2+^.

Besides the downstream events after Ca^2+^ influx, another set of studies indicated the important effects of different VDCCs (Voltaged-Dependent Calcium Channels) on Ca^2+^ signals. CaM can  bind with C-terminal tail of Cav1 channels, inactivating channel  opening in a Ca2+—influxdependent manner. CaM gather around the Cav1 entry with high concentration about mM level (Mori et al., 2004) and form a “nanodomain” which effectively slows down free Ca^2+^ from diffusing away (Tardross et al., 2013). This is consistent with the notion of “local signaling mode” in Cav1 channels (Wheeler et al., 2008) that Ca^2+^ signals are sensed locally around the channel entry and delivered to the nucleus. The local mode saves the Ca^2+^ from proprogating long distance and allows signals to be transducted with spatial locality.

To test whether Ca^2+^ signaling through carrier proteins is more feasible than simple diffusion, we built a model based on the Ca^2+^-CaM-CaMKII cascade to simulate the process from Ca^2+^ entering the cell till the nucleus response starts. Simulation results were examined at different conditions to further investigate 1) whether a concentrated CaM around the Cav1 channel affects signal transduction, 2) how different Ca^2+^ input patterns play a role, and 3) how the structural complexity of a CaMKII holoenzyme contributes to the signal transduction.

####Methods
The simulation was conducted using a user-modified version of Smoldyn. Smoldyn is a particle-based reaction-diffusion simulator and widely used in cell biology community (Andrews et al., 2010). Instead of computing molecule concentration, Smoldyn allows to track molecule positions individually at a fixed timestep.

In order to study the cascade at a cell scale without being too compoutational intensive, we simulate a narrow portion of the cell that extends from the cell surface to the nucleus in a pyramid shape. The pyramid geometry was used, considering it a better representation of a sample from the spherical cell. The base of the pyramid represents the cell membrane and the tip represents the center of the nucleus. All side surfaces are constructed as reflective boundary conditions, in order to keep the model system closed. The model consists of three compartments: the nanodomain, the cytosol and the nucleus. 

We focus on modeling how Ca^2^ ions enter the cell from the L-type Ca^2+^ channels, being taken up by calmodulin(CaM), forming a complex and then binding with \(\beta\) and \(\gamma\)CaMKIIs. Major players in the model include Ca^2+^, CaM, \(\beta\) and \(\gamma\)CaMKIIs. For the condition with mM level CaM in the nanodomain near the Ca^2+^ channels, we added membrane-attached neurogranin(Ng) to bind with apoCaMs and therefore to keep the nanodomain CaM at a mM level. Upon Ca^2+^ ions flow in, the bound apoCaMs can be released from Ng to react with Ca^2+^.

CaMKIIs are modeled as a 6-subunits ring complex.This is simplified from its original two layered 6-subunits rings structure, however still a fair approximation in terms capturing the dynamics among subunits. Reaction stages for a single subunit include Ca^2+^-CaM binding, autophosphorylation at Thr287, trapping of Ca^2+^-CaM and dephosphorylation. In particualr, a CaMKII subunit can bind with CaMs loaded varying number of Ca^2+^s. For \(\gamma\)CaMKIIs, due to its slow autophosphorylation, it was suggested that \(\gamma\)CaMKII sunbts get phosphorylated by \(\beta\)CaMKIIs. We included this intraholoenzyme interactions in the model.

Smoldyn was customized to simulate complexes such as CaMKIIs. Expanding reaction network for complexes was also attempted previously using BioNetGen, but the combanitoric complexity of the network results in high computional inefficiency to implement by reactions at a complex level. We moldified Smoldyn allow subunits of complex to diffuse collectively but react individually. Thus the reaction rules can be described for individual subunit, allowing to include more reaction details.

The model starts with steady-state concentration levels of Ca^2+^, CaM and CaMKIIs in different compartments so that there are no fluxes of free Ca^2+^ and CaM between compartments.  Concentration values were calculated using COPASI. A Ca^2+^ influx file was read into the model as a stimulus input. The file was previously generated using a whole neuron model, in which a sequence of postsynaptic potentiations accumulated and propagated to the soma, and the soma Ca^2+^ current was calculated in response to theta-burst action potential firings at the soma.

To set a time step, we used the fastest unbinding kinetic rate 160 ms^-1^ as a reference, which indicates a 0.000625 ms characteristic time.